### ISSUE TITLE
after connecting to ssh

### ISSUE THREAD

**Issue by jjab2020** [sykuang/docker-wine-x11-novnc#1]
Hello thank you very luch for your work,

I connect with ssh and the user xclient  with default password 1234 , doesn't have the privilage to anything for example if i type:
wine python-2.7.msi it show me wine is not owned by you.
Thank you very much to help me.

**Comment by sykuang** [comment]
This issue should be solved in commit d019395

**Comment by jjab2020** [comment]
Thank you very much,
I want to run python program using win32com of python in wine using your work How can i run python program in wine in docker and,return result in synology any help.
Thanks

**Comment by sykuang** [comment]
You can try to install windows python in the docker, and try to use the command "wine python ..." to execute your python script. Just a theory. I have never tried it...
