### ISSUE TITLE
How to use as base image

### ISSUE THREAD

**Issue by Nonobis** [sykuang/docker-wine-x11-novnc#4]
Hello,

 i am trying to use your image as base image.
Do you have a sample ?

I am trying to download a setup, install it and then run the installed program ?

**Comment by sykuang** [comment]
You can use the below command to launch the container.
```
docker run \
-v $HOME/Downloads:/home/docker/.wine/drive_c/Downloads \
-v $HOME/WinApp:/home/docker/.wine/drive_c/WinApp \
-p 8080:8080 \
-p 8081:22 \
sykuang/wine
```
And use the browser to visit http://$IP_TO_YOUR_DOCKERIP:8080; it will show a file explorer, letting you install the program via GUI. Once you have installed the program, you can execute the program by double-clicking the exe via file explorer.
