### ISSUE TITLE
Issues with environment variable mapping for directories on Synology

### ISSUE THREAD

**Issue by boktai1000** [sykuang/docker-wine-x11-novnc#6]
Hello there,

I love the idea of the docker image, but I'm having some issues getting the environment variables working properly for the directory mappings.

I've tried running the container as "root" as well as my user (with Home directories enabled in Synology) and unfortunately been unable to map these example directories:

-v $HOME/Downloads:/home/docker/.wine/drive_c/Downloads
-v $HOME/WinApp:/home/docker/.wine/drive_c/WinApp

My user is joined to the "docker" group
When running as root, it tries to map to /root/Downloads and /root/WinApp

Perhaps, you could share some insight on how your Synology is configured for better reference and required permissions.

Thank you

**Comment by sykuang** [comment]
Hi @boktai1000,
Thank you for your feedback. Since you are using the `root` user, the value of the environment variable `$HOME` will be `/root`. I recommend using absolute paths. For example, you can mount `/var/services/homes/sykuang/app` and `/volume1/docker/Downloads`.
